defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

exclude: [ '.sass-cache', 'node_modules', 'README.md', 'main.scss', 'package.json', 'gruntfile.js', 'npm-debug.log']
# highlighter: pygments